# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/cristian/OneDrive/2 anno/Laboratorio di programmazione/Feild_Progect"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/cristian/OneDrive/2 anno/Laboratorio di programmazione/Feild_Progect"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cristian/OneDrive/2 anno/Laboratorio di programmazione/Feild_Progect/CMakeFiles" "/home/cristian/OneDrive/2 anno/Laboratorio di programmazione/Feild_Progect//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/cristian/OneDrive/2 anno/Laboratorio di programmazione/Feild_Progect/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named regina

# Build rule for target.
regina: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 regina
.PHONY : regina

# fast build rule for target.
regina/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regina.dir/build.make CMakeFiles/regina.dir/build
.PHONY : regina/fast

#=============================================================================
# Target rules for targets named replay

# Build rule for target.
replay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replay
.PHONY : replay

# fast build rule for target.
replay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/build
.PHONY : replay/fast

#=============================================================================
# Target rules for targets named alfiere

# Build rule for target.
alfiere: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alfiere
.PHONY : alfiere

# fast build rule for target.
alfiere/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alfiere.dir/build.make CMakeFiles/alfiere.dir/build
.PHONY : alfiere/fast

#=============================================================================
# Target rules for targets named computer

# Build rule for target.
computer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 computer
.PHONY : computer

# fast build rule for target.
computer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer.dir/build.make CMakeFiles/computer.dir/build
.PHONY : computer/fast

#=============================================================================
# Target rules for targets named torre

# Build rule for target.
torre: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 torre
.PHONY : torre

# fast build rule for target.
torre/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torre.dir/build.make CMakeFiles/torre.dir/build
.PHONY : torre/fast

#=============================================================================
# Target rules for targets named pedone

# Build rule for target.
pedone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pedone
.PHONY : pedone

# fast build rule for target.
pedone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pedone.dir/build.make CMakeFiles/pedone.dir/build
.PHONY : pedone/fast

#=============================================================================
# Target rules for targets named eccezione

# Build rule for target.
eccezione: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eccezione
.PHONY : eccezione

# fast build rule for target.
eccezione/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eccezione.dir/build.make CMakeFiles/eccezione.dir/build
.PHONY : eccezione/fast

#=============================================================================
# Target rules for targets named cavallo

# Build rule for target.
cavallo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cavallo
.PHONY : cavallo

# fast build rule for target.
cavallo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cavallo.dir/build.make CMakeFiles/cavallo.dir/build
.PHONY : cavallo/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named scacchiera

# Build rule for target.
scacchiera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scacchiera
.PHONY : scacchiera

# fast build rule for target.
scacchiera/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/build
.PHONY : scacchiera/fast

#=============================================================================
# Target rules for targets named umano

# Build rule for target.
umano: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 umano
.PHONY : umano

# fast build rule for target.
umano/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umano.dir/build.make CMakeFiles/umano.dir/build
.PHONY : umano/fast

#=============================================================================
# Target rules for targets named casella

# Build rule for target.
casella: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 casella
.PHONY : casella

# fast build rule for target.
casella/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casella.dir/build.make CMakeFiles/casella.dir/build
.PHONY : casella/fast

#=============================================================================
# Target rules for targets named scacchi

# Build rule for target.
scacchi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scacchi
.PHONY : scacchi

# fast build rule for target.
scacchi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchi.dir/build.make CMakeFiles/scacchi.dir/build
.PHONY : scacchi/fast

replay.o: replay.cpp.o

.PHONY : replay.o

# target to build an object file
replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replay.cpp.o
.PHONY : replay.cpp.o

replay.i: replay.cpp.i

.PHONY : replay.i

# target to preprocess a source file
replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replay.cpp.i
.PHONY : replay.cpp.i

replay.s: replay.cpp.s

.PHONY : replay.s

# target to generate assembly for a file
replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replay.cpp.s
.PHONY : replay.cpp.s

src/alfiere.o: src/alfiere.cpp.o

.PHONY : src/alfiere.o

# target to build an object file
src/alfiere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/alfiere.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alfiere.dir/build.make CMakeFiles/alfiere.dir/src/alfiere.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/alfiere.cpp.o
.PHONY : src/alfiere.cpp.o

src/alfiere.i: src/alfiere.cpp.i

.PHONY : src/alfiere.i

# target to preprocess a source file
src/alfiere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/alfiere.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alfiere.dir/build.make CMakeFiles/alfiere.dir/src/alfiere.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/alfiere.cpp.i
.PHONY : src/alfiere.cpp.i

src/alfiere.s: src/alfiere.cpp.s

.PHONY : src/alfiere.s

# target to generate assembly for a file
src/alfiere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/alfiere.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alfiere.dir/build.make CMakeFiles/alfiere.dir/src/alfiere.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/alfiere.cpp.s
.PHONY : src/alfiere.cpp.s

src/casella.o: src/casella.cpp.o

.PHONY : src/casella.o

# target to build an object file
src/casella.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/casella.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/casella.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casella.dir/build.make CMakeFiles/casella.dir/src/casella.cpp.o
.PHONY : src/casella.cpp.o

src/casella.i: src/casella.cpp.i

.PHONY : src/casella.i

# target to preprocess a source file
src/casella.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/casella.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/casella.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casella.dir/build.make CMakeFiles/casella.dir/src/casella.cpp.i
.PHONY : src/casella.cpp.i

src/casella.s: src/casella.cpp.s

.PHONY : src/casella.s

# target to generate assembly for a file
src/casella.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/casella.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/casella.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casella.dir/build.make CMakeFiles/casella.dir/src/casella.cpp.s
.PHONY : src/casella.cpp.s

src/cavallo.o: src/cavallo.cpp.o

.PHONY : src/cavallo.o

# target to build an object file
src/cavallo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/cavallo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cavallo.dir/build.make CMakeFiles/cavallo.dir/src/cavallo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/cavallo.cpp.o
.PHONY : src/cavallo.cpp.o

src/cavallo.i: src/cavallo.cpp.i

.PHONY : src/cavallo.i

# target to preprocess a source file
src/cavallo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/cavallo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cavallo.dir/build.make CMakeFiles/cavallo.dir/src/cavallo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/cavallo.cpp.i
.PHONY : src/cavallo.cpp.i

src/cavallo.s: src/cavallo.cpp.s

.PHONY : src/cavallo.s

# target to generate assembly for a file
src/cavallo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/cavallo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cavallo.dir/build.make CMakeFiles/cavallo.dir/src/cavallo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/cavallo.cpp.s
.PHONY : src/cavallo.cpp.s

src/computer.o: src/computer.cpp.o

.PHONY : src/computer.o

# target to build an object file
src/computer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/computer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer.dir/build.make CMakeFiles/computer.dir/src/computer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/computer.cpp.o
.PHONY : src/computer.cpp.o

src/computer.i: src/computer.cpp.i

.PHONY : src/computer.i

# target to preprocess a source file
src/computer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/computer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer.dir/build.make CMakeFiles/computer.dir/src/computer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/computer.cpp.i
.PHONY : src/computer.cpp.i

src/computer.s: src/computer.cpp.s

.PHONY : src/computer.s

# target to generate assembly for a file
src/computer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/computer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer.dir/build.make CMakeFiles/computer.dir/src/computer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/computer.cpp.s
.PHONY : src/computer.cpp.s

src/eccezione.o: src/eccezione.cpp.o

.PHONY : src/eccezione.o

# target to build an object file
src/eccezione.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/eccezione.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eccezione.dir/build.make CMakeFiles/eccezione.dir/src/eccezione.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/eccezione.cpp.o
.PHONY : src/eccezione.cpp.o

src/eccezione.i: src/eccezione.cpp.i

.PHONY : src/eccezione.i

# target to preprocess a source file
src/eccezione.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/eccezione.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eccezione.dir/build.make CMakeFiles/eccezione.dir/src/eccezione.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/eccezione.cpp.i
.PHONY : src/eccezione.cpp.i

src/eccezione.s: src/eccezione.cpp.s

.PHONY : src/eccezione.s

# target to generate assembly for a file
src/eccezione.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/eccezione.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eccezione.dir/build.make CMakeFiles/eccezione.dir/src/eccezione.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/eccezione.cpp.s
.PHONY : src/eccezione.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pedone.o: src/pedone.cpp.o

.PHONY : src/pedone.o

# target to build an object file
src/pedone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/pedone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pedone.dir/build.make CMakeFiles/pedone.dir/src/pedone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/pedone.cpp.o
.PHONY : src/pedone.cpp.o

src/pedone.i: src/pedone.cpp.i

.PHONY : src/pedone.i

# target to preprocess a source file
src/pedone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/pedone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pedone.dir/build.make CMakeFiles/pedone.dir/src/pedone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/pedone.cpp.i
.PHONY : src/pedone.cpp.i

src/pedone.s: src/pedone.cpp.s

.PHONY : src/pedone.s

# target to generate assembly for a file
src/pedone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/pedone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pedone.dir/build.make CMakeFiles/pedone.dir/src/pedone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/pedone.cpp.s
.PHONY : src/pedone.cpp.s

src/re.o: src/re.cpp.o

.PHONY : src/re.o

# target to build an object file
src/re.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/re.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/src/re.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/re.cpp.o
.PHONY : src/re.cpp.o

src/re.i: src/re.cpp.i

.PHONY : src/re.i

# target to preprocess a source file
src/re.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/re.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/src/re.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/re.cpp.i
.PHONY : src/re.cpp.i

src/re.s: src/re.cpp.s

.PHONY : src/re.s

# target to generate assembly for a file
src/re.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/re.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/src/re.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/re.cpp.s
.PHONY : src/re.cpp.s

src/regina.o: src/regina.cpp.o

.PHONY : src/regina.o

# target to build an object file
src/regina.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regina.dir/build.make CMakeFiles/regina.dir/src/regina.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/regina.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/regina.cpp.o
.PHONY : src/regina.cpp.o

src/regina.i: src/regina.cpp.i

.PHONY : src/regina.i

# target to preprocess a source file
src/regina.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regina.dir/build.make CMakeFiles/regina.dir/src/regina.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/regina.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/regina.cpp.i
.PHONY : src/regina.cpp.i

src/regina.s: src/regina.cpp.s

.PHONY : src/regina.s

# target to generate assembly for a file
src/regina.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regina.dir/build.make CMakeFiles/regina.dir/src/regina.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/regina.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/regina.cpp.s
.PHONY : src/regina.cpp.s

src/scacchiera.o: src/scacchiera.cpp.o

.PHONY : src/scacchiera.o

# target to build an object file
src/scacchiera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/scacchiera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/scacchiera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchi.dir/build.make CMakeFiles/scacchi.dir/src/scacchiera.cpp.o
.PHONY : src/scacchiera.cpp.o

src/scacchiera.i: src/scacchiera.cpp.i

.PHONY : src/scacchiera.i

# target to preprocess a source file
src/scacchiera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/scacchiera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/scacchiera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchi.dir/build.make CMakeFiles/scacchi.dir/src/scacchiera.cpp.i
.PHONY : src/scacchiera.cpp.i

src/scacchiera.s: src/scacchiera.cpp.s

.PHONY : src/scacchiera.s

# target to generate assembly for a file
src/scacchiera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/scacchiera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/scacchiera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchi.dir/build.make CMakeFiles/scacchi.dir/src/scacchiera.cpp.s
.PHONY : src/scacchiera.cpp.s

src/torre.o: src/torre.cpp.o

.PHONY : src/torre.o

# target to build an object file
src/torre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/torre.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torre.dir/build.make CMakeFiles/torre.dir/src/torre.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/torre.cpp.o
.PHONY : src/torre.cpp.o

src/torre.i: src/torre.cpp.i

.PHONY : src/torre.i

# target to preprocess a source file
src/torre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/torre.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torre.dir/build.make CMakeFiles/torre.dir/src/torre.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/torre.cpp.i
.PHONY : src/torre.cpp.i

src/torre.s: src/torre.cpp.s

.PHONY : src/torre.s

# target to generate assembly for a file
src/torre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/torre.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/torre.dir/build.make CMakeFiles/torre.dir/src/torre.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/torre.cpp.s
.PHONY : src/torre.cpp.s

src/umano.o: src/umano.cpp.o

.PHONY : src/umano.o

# target to build an object file
src/umano.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/umano.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/umano.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umano.dir/build.make CMakeFiles/umano.dir/src/umano.cpp.o
.PHONY : src/umano.cpp.o

src/umano.i: src/umano.cpp.i

.PHONY : src/umano.i

# target to preprocess a source file
src/umano.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/umano.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/umano.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umano.dir/build.make CMakeFiles/umano.dir/src/umano.cpp.i
.PHONY : src/umano.cpp.i

src/umano.s: src/umano.cpp.s

.PHONY : src/umano.s

# target to generate assembly for a file
src/umano.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/umano.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/umano.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umano.dir/build.make CMakeFiles/umano.dir/src/umano.cpp.s
.PHONY : src/umano.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alfiere"
	@echo "... casella"
	@echo "... cavallo"
	@echo "... computer"
	@echo "... eccezione"
	@echo "... pedone"
	@echo "... re"
	@echo "... regina"
	@echo "... replay"
	@echo "... scacchi"
	@echo "... scacchiera"
	@echo "... torre"
	@echo "... umano"
	@echo "... replay.o"
	@echo "... replay.i"
	@echo "... replay.s"
	@echo "... src/alfiere.o"
	@echo "... src/alfiere.i"
	@echo "... src/alfiere.s"
	@echo "... src/casella.o"
	@echo "... src/casella.i"
	@echo "... src/casella.s"
	@echo "... src/cavallo.o"
	@echo "... src/cavallo.i"
	@echo "... src/cavallo.s"
	@echo "... src/computer.o"
	@echo "... src/computer.i"
	@echo "... src/computer.s"
	@echo "... src/eccezione.o"
	@echo "... src/eccezione.i"
	@echo "... src/eccezione.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pedone.o"
	@echo "... src/pedone.i"
	@echo "... src/pedone.s"
	@echo "... src/re.o"
	@echo "... src/re.i"
	@echo "... src/re.s"
	@echo "... src/regina.o"
	@echo "... src/regina.i"
	@echo "... src/regina.s"
	@echo "... src/scacchiera.o"
	@echo "... src/scacchiera.i"
	@echo "... src/scacchiera.s"
	@echo "... src/torre.o"
	@echo "... src/torre.i"
	@echo "... src/torre.s"
	@echo "... src/umano.o"
	@echo "... src/umano.i"
	@echo "... src/umano.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

